## 🛠️ Feature Engineering & Cleaning Backlog
### Remove Data
- [ ] `fuel_type`: Standardize missing indicators. Map '–' and 'not supported' to `NaN`. Impute missing fields using the mode ('Gasoline') or an explicit 'Unknown' category string. One-hot encode the final 5 clean variants.
- [ ] ### 1. missing data 
- [ ] `milage`: Strip "mi." and commas, coerce errors to NaN, impute with median.
- [ ] `price` (Target): Remove "$" and commas, drop rows where target is missing or $1.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("used_cars.csv")
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   str
 1   model         4009 non-null   str
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   str
 4   fuel_type     3839 non-null   str
 5   engine        4009 non-null   str
 6   transmission  4009 non-null   str
 7   ext_col       4009 non-null   str
 8   int_col       4009 non-null   str
 9   accident      3896 non-null   str
 10  clean_title   3413 non-null   str
 11  price         4009 non-null   str
dtypes: int64(1), str(11)
memory usage: 376.0 KB

In [4]:
df.describe()

        model_year
count  4009.000000
mean   2015.515590
std       6.104816
min    1974.000000
25%    2012.000000
50%    2017.000000
75%    2020.000000
max    2024.000000

In [18]:
from pandas.api.types import is_string_dtype, is_object_dtype
for col in df.columns:
    if is_string_dtype(df[col]) or is_object_dtype(df[col]):
        print(f"Text Column: {col:<15} Unique Values: {df[col].nunique()}")

Text Column: brand           Unique Values: 57
Text Column: model           Unique Values: 1898
Text Column: milage          Unique Values: 2818
Text Column: fuel_type       Unique Values: 7
Text Column: engine          Unique Values: 1146
Text Column: transmission    Unique Values: 62
Text Column: ext_col         Unique Values: 319
Text Column: int_col         Unique Values: 156
Text Column: accident        Unique Values: 2
Text Column: clean_title     Unique Values: 1
Text Column: price           Unique Values: 1569

In [20]:
df.accident.value_counts()

accident
None reported                             2910
At least 1 accident or damage reported     986
Name: count, dtype: int64

In [24]:
df.fuel_type.unique()

<StringArray>
[ 'E85 Flex Fuel',       'Gasoline',         'Hybrid',              nan,
         'Diesel', 'Plug-In Hybrid',              '–',  'not supported']
Length: 8, dtype: str

In [25]:
df.fuel_type.value_counts()

fuel_type
Gasoline          3309
Hybrid             194
E85 Flex Fuel      139
Diesel             116
–                   45
Plug-In Hybrid      34
not supported        2
Name: count, dtype: int64

In [26]:
df.fuel_type.mode()

0    Gasoline
Name: fuel_type, dtype: str